steps:
  - name: python
    entrypoint: python
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['start']